baseURL = "https://master.d2j7dkmzeynjw4.amplifyapp.com/"
languageCode = "en-us"
title = "Hi, My Name Is Zaqi"
theme ="hello-friend"
defaultTheme = "dark"
paginate     = 10

<div id="disqus_thread"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    
    var disqus_config = function () {
    this.page.url = https://master.d2j7dkmzeynjw4.amplifyapp.com/;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = zaqiweb; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://https-master-d2j7dkmzeynjw4-amplifyapp-com.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<script id="dsq-count-scr" src="//https-master-d2j7dkmzeynjw4-amplifyapp-com.disqus.com/count.js" async></script>

[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
[[menu.main]]
    identifier = "post"
    name       = "Post"
    url        = "/posts"



# sosial icons

[[params.social]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCi7TMQDz0htxL4P-PDd1jIg"
[[params.social]]
  name = "email"
  url = "mailto:ibnuzacxyy@gmail.com"
[[params.social]]
  name = "github"
  url = "https://github.com/zaqi-design"
[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/zacxyy_ibnu"
[[params.social]]
  name = "facebook"
  url = "https://www.facebook.com/djaki.ibnu/"
